services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD={PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin/data:rw"
    ports:
      - "8080:80"
volumes:
  pgadmin_data: